paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: Productos no encontrados
        "500":
          description: Error interno del servidor al consultar los productos
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      parameters:
        - name: Product
          in: body
          description: Producto a crear
          required: true
          schema:
            type: Object
            $ref: "#/components/schemas/ProductToCreateOrModify"
      responses:
        "201":
          description: Producto creado
          content:
            application/json:
              schema:
                type: Object
                $ref: "#/components/schemas/Product"
        "401":
          description: Llave duplicada. Código ya existente
        "500":
          description: Error interno del servidor al crear producto
  /api/products/{id}:
    get:
      summary: Obtener un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: Id del producto a buscar
      responses:
        "200":
          description: Producto obtenido
          content:
            application/json:
              schema:
                type: Object
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor al consultar producto
    put:
      summary: Modificar un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: Id del usuario a buscar
        - name: Product
          in: body
          description: El producto a modificar
          required: true
          schema:
            type: Object
            $ref: "#/components/schemas/ProductToCreateOrModify"
      responses:
        "200":
          description: Producto modificado
          content:
            application/json:
              schema:
                type: Object
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor al modificar producto
    delete:
      summary: Eliminar un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $type: String
          description: Id del producto a eliminar
      responses:
        "200":
          description: Producto eliminado
          content:
            application/json:
              schema:
                type: Object
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor al consultar producto

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado por MongoDB
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        category:
          type: String
          description: Categoria con la que se identifica el tipo de producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad de productos disponibles
        code:
          type: String
          description: Codigo unico del producto
        thumbnail:
          type: String
          description: Imagen del producto

    ProductToCreateOrModify:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        category:
          type: String
          description: Categoria a la que pertenece el producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Cantidad de productos disponibles
        code:
          type: String
          description: Codigo unico del producto
        thumbnail:
          type: String
          description: Imagen del producto
